### ISSUE TITLE
Dígitos verificadores

### ISSUE THREAD

**Issue by solstag** [lkraider/iban-generator#3]
Ni!

Seria bom explicitar na interface que o número da agência deve ser preenchido SEM dígito verificador, enquanto o da conta deve ser preenchido COM dígito verificador.

Abs e obrigado pelo app!

**Comment by abensur** [comment]
Precisei do serviço hoje, e precisei sair do app pra responder essa mesma dúvida.
Abri um PR com esses avisos: https://github.com/lkraider/iban-generator/pull/4
